config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/marcmath/download_TABOO_waveforms:
      branch: main
      repo: https://github.com/marcmath/download_TABOO_waveforms
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/marcmath/download_TABOO_waveforms git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-lime-tapir.sh
        container: qc.acc_sloppy-alizarin-zebra
  QC.Doc:
    repos:
      github.com/marcmath/download_TABOO_waveforms find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-scarlet-rattlesnake.sh
        container: qc.doc_lumpy-black-mist
      github.com/marcmath/download_TABOO_waveforms git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-bistre-warthog.sh
        container: qc.doc_seedy-asparagus-whale
      github.com/marcmath/download_TABOO_waveforms markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-chestnut-tarantula.sh
        container: qc.doc_silly-aqua-horse
  QC.Lic:
    repos:
      github.com/marcmath/download_TABOO_waveforms licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-gamboge-tetra.sh
        container: qc.lic_hasty-pear-burmese
  QC.Sec:
    repos:
      github.com/marcmath/download_TABOO_waveforms bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-green-pig.sh
        container: qc.sec_stealthy-heliotrope-bombay
  QC.Sty:
    repos:
      github.com/marcmath/download_TABOO_waveforms flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-carmine-cow.sh
        container: qc.sty_pokey-chocolate-havanese
  QC.Uni:
    repos:
      github.com/marcmath/download_TABOO_waveforms pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-firebrick-stoat.sh
        container: qc.uni_skanky-white-urchin
  QC.Ver:
    repos:
      github.com/marcmath/download_TABOO_waveforms get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-amethyst-bison.sh
        container: qc.ver_cozy-smalt-dhole
timeout: 5400
