config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/marcmath/download_TABOO_waveforms:
      branch: 1.1.0
      repo: https://github.com/marcmath/download_TABOO_waveforms
      subfolder: DTC74/WF7403/ST740304/src
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/marcmath/download_TABOO_waveforms git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-asparagus-oyster.sh
        container: qc.acc_crabby-mauve-binturong
  QC.Doc:
    repos:
      github.com/marcmath/download_TABOO_waveforms find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-salmon-eel.sh
        container: qc.doc_gimpy-violet-gar
      github.com/marcmath/download_TABOO_waveforms git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-mustard-coati.sh
        container: qc.doc_snippy-grey-beagle
      github.com/marcmath/download_TABOO_waveforms markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-razzmatazz-gibbon.sh
        container: qc.doc_flaky-coral-gecko
  QC.Lic:
    repos:
      github.com/marcmath/download_TABOO_waveforms licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-cyan-squid.sh
        container: qc.lic_pretty-grey-budgerigar
  QC.Sec:
    repos:
      github.com/marcmath/download_TABOO_waveforms bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-sangria-monster.sh
        container: qc.sec_wiggy-magenta-russel
  QC.Sty:
    repos:
      github.com/marcmath/download_TABOO_waveforms flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-plum-devil.sh
        container: qc.sty_snoopy-white-impala
  QC.Uni:
    repos:
      github.com/marcmath/download_TABOO_waveforms commands:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-thistle-dalmatian.sh
        container: qc.uni_skinny-lilac-wolf
  QC.Ver:
    repos:
      github.com/marcmath/download_TABOO_waveforms get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cerise-catfish.sh
        container: qc.ver_snazzy-lilac-iguana
timeout: 5400
